# Generated by Django 5.2.7 on 2025-10-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
